name: EKS Deployment

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build and Push Docker Image
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/view-app:v1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/view-app:v1

  # Job 2: Deploy to EC2 and EKS
  deploy:
    name: Deploy to EC2 and EKS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Transfer code to EC2
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_IP }}
          #EC2_KEY: ${{ secrets.EC2_PEM }}
        run: |
          mkdir -p ~/.ssh 
          echo "${{ secrets.EC2_PEM }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          scp -o StrictHostKeyChecking=no -i ~/.ssh/ec2_key.pem -r ./* $EC2_USER@$EC2_HOST:/home/ubuntu/
          ssh -i ~/.ssh/ec2_key.pem $EC2_USER@$EC2_HOST

    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region us-east-1

      - name: Update EKS deployment
        run: |
          kubectl set image deployment/go-server-deployment go-server-ctnr=${{ secrets.DOCKER_USERNAME }}/view-app:v1

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yml

  verify:
    name: Verify Deployment
    runs-on: ubuntu-latest
    needs: deploy

    steps:        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: 'us-east-1'

      - name: Update kubeconfig
        run: |
         aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region us-east-1
     # - name: EKS configure
      #  run: |
       #   aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region us-east-1

      - name: Verify Deployment
        run: |
        
          ssh -i "${{ secrets.EC2_PEM }}" $EC2_USER@$EC2_HOST
          cd ingress
          kubectl apply -f nginx-controller.yml -n ingress-nginx
          kubectl apply -f service.yml -n ingress-nginx
          kubectl apply -f ingress.yml -n ingress-nginx
          kubectl get deployments
          kubectl get pods
          kubectl get svc
       #   kubectl get ingresses

      #- name: Apply Ingress Controller
      #  run: |
          #kubectl apply -f ingress/nginx-controller.yml
          #kubectl apply -f ingress/ingress.yml

      - name: Verify Ingress and NGINX
        run: |
          kubectl get deployments -n ingress-nginx
          kubectl get services -n ingress-nginx
          kubectl get ingresses
